stages:
  - mirror
  - test

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/canon-g7x-photosorter.git master

checkstyle:
  stage: test
  tags:
    - pycodesyle
  script:
    - pycodestyle .
